---
  name: Publish Joomla package

  on:
    push:
      tags: [ 'dev-release', 'v*' ]
      branches: [ disabled ]

  jobs:
    publish:
      name: Build Joomla package
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.4
        - name: Install zip
          uses: montudor/action-zip@v1
        - name: Zip Joomla plugin
          run: zip -qq -r plg_content_markasread .
          working-directory: plugins/content/markasread/
        - name: Move plugin archive
          run: mv plugins/content/markasread/plg_content_markasread.zip packages/
        - name: Zip Joomla component
          run: zip -qq -r com_markasread .
          working-directory: component/com_markasread
        - name: Move plugin archive
          run: mv component/com_markasread/com_markasread.zip packages/
        - name: Zip Joomla package
          uses: montudor/action-zip@v1
          with:
            args: zip -qq -r pkg_markasread.zip pkg_markasread.xml package.installer.php packages
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@2.2.1
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            overwrite: true
            asset_name: pkg_markasread.zip
            file: pkg_markasread.zip
            body: ''
            tag: ${{ github.ref }}
